### PR TITLE
Limit the width of the swipe list

### LINKED ISSUE #174: Optimize map view for tablets
It's basically only about the swiper at the bottom.

See: https://zpl.io/2vnRjdj

### PR DESCRIPTION
**Pull request by VaclavSir**
Close #174 
screen shot 2018-01-16 at 11 38 36

---
Please check this before merging (do not delete this checklist):

- [ ] it works in landscape and portrait mode
- [ ] it uses `cacheConfig.force=true` if offline access doesn't make sense

### CODE REVIEW

**Comment by VaclavSir** [comment]
I fixed the visibility of the next hotel. I don't quite understand the note about `getLandscapeThreshold`, do you mean the maxWidth should be applied only in landscape mode?

screen shot 2018-01-16 at 16 56 49

**Comment by mrtnzlml** [comment]
Landscape threshold essentially solves the question "Why did you choose _668_? Why not _686_? Is it OK for every tablet?". Everything below this threshold is OK for portrait mode and everything above is OK for landscape mode. The name is stupid - feel free to make it less stupid.

This is basically how `Layout` works - it's wide open in portrait mode and it keeps its width for large devices. In the future, we can improve this method significantly by adding devices resolutions map or something like that - not important now.

I just don't like this next magic number constant (even the magic constant in `Layout` component is wrong).

**Comment by mrtnzlml** [comment]
Please fix the unhappy CI... 🙂

**Comment by VaclavSir** [comment]
I didn't chose 668, I copied it from Zeplin... I comforted the CI, now it's happy. 😸

**Comment by mrtnzlml** [comment]
Zeplin is not really designed for every device... :)

**Pull request merged**
