### PR TITLE
Refactor map component

### PR DESCRIPTION
**Pull request by jaroslav-kubicek**

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Please test these changes in [Expo](https://docs.expo.io/versions/latest/introduction/installation.html#mobile-client-expo-for-ios-and-android) after build has finished:

  QR Code

**Comment by jaroslav-kubicek** [comment]
As I'm not able to achieve workable swipe cards, I'm giving up on this PR, removing previous attempt with `react-native-swiper` and leaving just refactoring of the component.

**Comment by jaroslav-kubicek** [comment]
Just as an explanation,  `index` prop in `react-native-swiper` can't simply be updated - it's indented only as *initial* value

**Comment by mrtnzlml** [comment]
> I'm giving up

I don't know what this means. This is not in Kiwi.com vocabulary... 🙂 

Also, please be more careful with the commit message. Message "Add swipe cards to the map" is not really accurate in this case.

**Pull request closed without merging**
