### PR TITLE
Use max price from all available hotels query

### LINKED ISSUE #197: Show price range according to real data
Currently, the price range in the filter has fixed values (0-300 EUR) - let's fetch real max/min values from api and adjust these values accordingly.

### PR DESCRIPTION
**Pull request by tbergq**
Closes #197 

---
Please check this before merging (do not delete this checklist):

- [ ] it works in landscape and portrait mode
- [ ] it uses `cacheConfig.force=true` if offline access doesn't make sense

### CODE REVIEW

**Comment by mrtnzlml** [comment]
There is still one issue - application freeze when you try to click before it's loaded. It happened to me in the first 2 seconds of testing so it should be resolved somehow... :)

**Comment by tbergq** [comment]
Ok, I will look into it

**Comment by tbergq** [comment]
Seems it was the inital reducer value of Number.MAX_SAFE_INTEGER that made the ui freeze.

**Comment by mrtnzlml** [comment]
What do you mean? It doesn't work in RN? How did you discover it so fast?

**Comment by tbergq** [comment]
I had a hunch that it could be this, since it opens when the value has been changed. 

Probably the slider component that does not like a number that big (just guessing)

**Comment by mrtnzlml** [comment]
@tbergq Yould you please rebase it? There are changes in `PriceFilter` and I am not sure how to fix it properly.

**Comment by tbergq** [comment]
Rebaes

**Comment by mrtnzlml** [comment]
Good, integrated. Thanks.

**Pull request closed without merging**
