### PR TITLE
WIP: Pick first location on confirm if none is selected

### PR DESCRIPTION
**Pull request by tbergq**

### CODE REVIEW

**Comment by tbergq** [comment]
I would like to wait a little bit with this one. I think the problem where the styling of the confirm button does not update is linked to our text component. I thought it might be a rerender issue with `react-navigation`

**Comment by mrtnzlml** [comment]
@tbergq Can you please replicate this issue in a minimal example so we can fix it?

**Comment by tbergq** [comment]
Yes, I will look into it soon, make a playground for it, and try to solve it

**Comment by tbergq** [comment]
closing this since we confirm on click on first location

**Pull request closed without merging**
