### PR TITLE
Add less embarrassing loading indicator

### PR DESCRIPTION
**Pull request by mrtnzlml**
Main inspiration: https://www.kiwi.com/storybook/?selectedKind=Components%2FButton&selectedStory=loading-blue&full=0&down=1&left=1&panelRight=1&downPanel=storybook%2Factions%2Factions-panel (I basically copy pasted the behavior)

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Please test these changes in [Expo](https://docs.expo.io/versions/latest/introduction/installation.html#mobile-client-expo-for-ios-and-android) after build has finished:

  QR Code

**Comment by mrtnzlml** [comment]
It is not used. But I did not remove it in this PR. I can probably do that (tomorrow). Or you can during merge... :)

**Comment by mrtnzlml** [comment]
The idea behind why I didn't do it was: It doesn't have to be necessary in one PR. I am adding a new component and they can live together (next to each other). I can keep the better one and remove the old one later.

**Comment by jaroslav-kubicek** [comment]
ok, that's sufficient explanation, I was curious whether it was intentional or just forgotten

**Comment by mrtnzlml** [comment]
> Note think about removing old simple loader

Ok, fuck it: https://github.com/kiwicom/react-native-app/pull/68 🙂

**Pull request merged**
