### PR TITLE
Fix no partial error shown bug

### LINKED ISSUE #503: PartialError not showing

### PR DESCRIPTION
**Pull request by tbergq**
closes #503

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Can you please add tests for this?

**Comment by tbergq** [comment]
Sure, I will do that

**Comment by tbergq** [comment]
tests added, please check again @mrtnzlml

**Comment by tbergq** [comment]
> Do I understand correctly this probably changed with Relay upgrade

It is the only reasonable explanation I can think of

**Pull request merged**
